name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install hxcpp-debug-server
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools

      - name: Configure Android SDK/NDK
        run: |
          echo "ANDROID_SDK=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk-bundle" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile APK
        run: haxelib run lime build android -debug --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuild
          path: export/debug/android/bin/app/build/outputs/apk/debug/app-debug.apk
